---
- name: CONFIGURE AMR INTERFACE IP
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
    - name: CONFIGURE GIGABITETHERNET2 IP ADDRESS
      ios_config:
        parents: "interface GigabitEthernet2"
        lines:
          - ip address 202.6.255.1 255.255.255.252
          - no shutdown

    - name: SHOW IP INTERFACE BRIEF
      ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: SAVE OUTPUT
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "ios_configurations/ip_interface_summary_CSR1kv.txt"
